# Base configuration
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
markdown: kramdown
highlighter: rouge

collections:
  pages:
    output: true
    permalink: /:path/

# Title
name: Visual Relationship Detection
subtitle: Term Project for CS 6476 - Computer Vision
authors: Arvind Krishnakumar, Asawaree Bhide, Divyansh Roy, Shubhangi Upasani

# When using this template with a project page set the baseurl to '/project-name'
# For user/organization pages set this to an empty string
# When working locally use jekyll serve --baseurl '' so that you can view everything at localhost:4000
# See http://jekyllrb.com/docs/github-pages/ for more info
#baseurl: ''
baseurl: '/vrd6476'

# Author/Organization info to be displayed in the templates
author:
  name: Arvind
  url: http://github.com/akrishna77

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl:
logoalt:

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Home
  url: ./
  internal: true
- text: Proposal
  url: proposal/
  internal: true
# - text: Problem Statement
#   url: problem_statement/
#   internal: true
# - text: Approach
#   url: approach/
#   internal: true
# - text: Experiments
#   url: experiments/
#   internal: true
# - text: Evaluation
#   url: evaluation/
#   internal: true
# - text: References
#   url: references/
#   internal: true
- text: houghlepuff Repo
  url: https://github.com/akrishna77/houghlepuff
  internal: false

# Repo list
# List repos that you would like to appear on the homepage here
repos:
- name: Houghlepuff
  description: Visual Relationship Detection
  url: https://github.com/akrishna77/houghlepuff

# Style Variables
brand_color: "#2cb34a"

# Offline caching
offline_cache: false
cache_name: Houghlepuff-v1.1
